package com.example.lab5.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006E1C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF95F990)
val md_theme_light_onPrimaryContainer = Color(0xFF002204)
val md_theme_light_secondary = Color(0xFF52634F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E8CF)
val md_theme_light_onSecondaryContainer = Color(0xFF101F0F)
val md_theme_light_tertiary = Color(0xFF386568)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCEBEE)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_surface = Color(0xFFFCFDF6)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D8)

val md_theme_dark_primary = Color(0xFF79DC77)
val md_theme_dark_onPrimary = Color(0xFF00390A)
val md_theme_dark_primaryContainer = Color(0xFF005313)
val md_theme_dark_onPrimaryContainer = Color(0xFF95F990)
val md_theme_dark_secondary = Color(0xFFB9CCB4)
val md_theme_dark_onSecondary = Color(0xFF243423)
val md_theme_dark_secondaryContainer = Color(0xFF3A4B38)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E8CF)
val md_theme_dark_tertiary = Color(0xFFA0CFD2)
val md_theme_dark_onTertiary = Color(0xFF00373A)
val md_theme_dark_tertiaryContainer = Color(0xFF1E4D50)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
